import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import Navbar from "@/components/navbar.component";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <Navbar/>
        {children}</body>
    </html>
  );
}
